config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "employees#index"
  resources :employees
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
  # validates :name, presence: true
  require 'csv'

    def self.to_csv
      employees = all
        CSV.generate do | csv|
          csv << column_names
            employees.each do | employee |
              csv << employee.attributes.values_at(*column_names)
            end 
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
    respond_to do | format |
      format.html
      format.csv{ send_data Employee.to_csv, filename: "Employee-#{DateTime.now.strftime("%d%m%y%h%m")}.csv"}
    end
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.create(employee_params)
    if @employee.save
      redirect_to @employee
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params)
      redirect_to @employee
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to root_path
  end

  private
  def employee_params
    params.require(:employee).permit(:name, :email, :designation, :date_of_birth, :joining_date, :company_name, :company_address, :father_name,:mother_name, :father_contact_no, :mother_contact_no, :joining_date, :house_no, :area_lankmark, :city, :state, :pin_code, :gender )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/edit.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Employee Portal</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<%= form_with model: @employee do |form |%>
<nav class="navbar navbar-dark bg-dark ">
<strong><h3 class="text-white"> Employee<snap class="text-primary">Portal<snap></h3></strong>
</nav>
<h3 class="text-center">Update Employee Details</h3>

<div class="container bg-light shadow p-3 mb-5 bg-white rounded">
<table class="table">
<div>
<h4>Employee Details </h4>
<div style="text-align:right"><%= link_to 'back',@employee, class:"btn btn-primary" %><div><div>
<tr>
  <td>
  <%= form.label :name %><br>
  <%= form.text_field :name , class: "form-control"%>
  </td>
  <td>
  <%= form.label :email %><br>
  <%= form.text_field :email , class: "form-control"%>
  </td>
</tr>
<tr>
  <td>
  <%= form.label :designation %><br>
  <%= form.text_field :designation , class: "form-control"%>
  </td>
  <td>
  <%= form.label :joining_date %><br>
  <%= form.date_field :joining_date , class: "form-control"%>
  </td>
</tr>
<tr>
  <td>
  <%= form.label :company_name %><br>
  <%= form.text_area :company_name , class: "form-control"%>
  </td>
  <td>
  <%= form.label :company_address %><br>
  <%= form.text_area :company_address , class: "form-control"%>
  </td>
</tr>
</table>
</div>
<div class="container bg-light shadow p-3 mb-5 bg-white rounded">
<h4>Personal Details</h4>
<table class="table">
<tr>
  <td>
  <%= form.label :date_of_birth %><br>
  <%= form.date_field :date_of_birth , class: "form-control"%>
  </td>
  <td>
  <%= form.label :contact_no %><br>
  <%= form.telephone_field :contact_no , class: "form-control"%>
  </td>
</tr>
<tr>
  <td>
  <%= form.label :gender %><br>
  <%= form.label :gender, "Male" %>
  <%= form.radio_button :gender , class:"form-check"%>
  <%= form.label :gender, "Female"%>
  <%= form.radio_button :gender , class:"form-check"%>
  </td>
  <td>
  <%= form.label :contact_no %><br>
  <%= form.telephone_field :contact_no , class: "form-control"%>
  </td>
</tr>
<tr>
  <td>
  <%= form.label :father_name %><br>
  <%= form.text_field :father_name , class: "form-control"%>
  </td>
  <td>
  <%= form.label :mother_name %><br>
  <%= form.text_field :mother_name , class: "form-control"%>
  </td>
</tr>
<tr>
  <td>
  <%= form.label :father_contact_no %><br>
  <%= form.telephone_field :father_contact_no , class: "form-control"%>
  </td>
  <td>
  <%= form.label :mother_contact_no %><br>
  <%= form.telephone_field :mother_contact_no , class: "form-control"%>
  </td>
</tr>
</table>
</div>
<div class="container bg-light shadow p-3 mb-5 bg-white rounded">
<h4> Address Details </h4>
<table class="table">
<tr>
  <td>
  <%= form.label :house_no %><br>
  <%= form.text_field :house_no , class: "form-control"%>
  </td>
  <td>
  <%= form.label :area_lankmark %><br>
  <%= form.text_field :area_lankmark , class: "form-control"%>
  </td>
</tr>
<tr>
  <td>
  <%= form.label :city %><br>
  <%= form.text_field :city , class: "form-control"%>
  </td>
  <td>
  <%= form.label :pin_code %><br>
  <%= form.text_field :pin_code , class: "form-control"%>
  </td>
 <td>
  <%= form.label :state %>
  <%= form.text_field :state , class: "form-control"%>
  </td>
</tr>

</table>
<%= form.submit  class:"btn btn-success" %>
</div>

<% end %>


</body>
</html>

app/views/employees/index.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Employee Portal</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-dark bg-dark ">
<strong><h3 class="text-white"> Employee<snap class="text-primary">Portal<snap></h3></strong>
<div>
<%= link_to 'New Employee' , new_employee_path, class:"btn btn-primary"%>
<%= link_to 'Export', employees_path(format: 'csv'), class:"btn btn-warning" %>
</div>
</nav>
<div class="container">
<h3 class="text-center">Employee Listing</h3>
<table class="table">
<thead>
<th>Name</th>
<th>Email</th>
<th>Designation </th>
<th></th>
</thead>
<% @employees.each do |employee|%>
<tr>
<td><%= employee.name %></td>
<td><%= employee.email %></td>
<td><%= employee.designation %></td>
<td><%= link_to 'View', employee, class:"btn btn-success" %></td>
</tr>
<% end %>
</table>
</div>
</body>
</html>

app/views/employees/new.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Employee Portal</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<%= form_with model: @employee do |form |%>
<nav class="navbar navbar-dark bg-dark ">
<strong><h3 class="text-white"> Employee<snap class="text-primary">Portal<snap></h3></strong>
</nav>
<h3 class="text-center">New Employee listing </h3>

<div class="container bg-light shadow p-3 mb-5 bg-white rounded">

<table class="table">
<div>
<h4>Employee Details </h4>
<div style="text-align:right"><%= link_to 'back', root_path, class:"btn btn-primary" %><div><div>
<tr>
  <td>
  <%= form.label :name %><br>
  <%= form.text_field :name , class: "form-control"%>
  <% @employee.errors.full_messages_for(:name).each do |message |%>
    <span><small class="text-danger"><%= message %></small></span>
  <% end %>
 
  </td>
  <td>
  <%= form.label :email %><br>
  <%= form.text_field :email , class: "form-control"%>
  </td>
</tr>
<tr>
  <td>
  <%= form.label :designation %><br>
  <%= form.text_field :designation , class: "form-control"%>
  </td>
  <td>
  <%= form.label :joining_date %><br>
  <%= form.date_field :joining_date , class: "form-control"%>
  </td>
</tr>
<tr>
  <td>
  <%= form.label :company_name %><br>
  <%= form.text_area :company_name , class: "form-control"%>
  </td>
  <td>
  <%= form.label :company_address %><br>
  <%= form.text_area :company_address , class: "form-control"%>
  </td>
</tr>
</table>
</div>
<div class="container bg-light shadow p-3 mb-5 bg-white rounded">
<h4>Personal Details</h4>
<table class="table">
<tr>
  <td>
  <%= form.label :date_of_birth %><br>
  <%= form.date_field :date_of_birth , class: "form-control"%>
  </td>
  <td>
  <%= form.label :contact_no %><br>
  <%= form.telephone_field :contact_no , class: "form-control"%>
  </td>
</tr>
<tr>
  <td>
  <%= form.label :gender %><br>
  <%= form.label :gender, "Male" %>
  <%= form.radio_button :gender , class:"form-check"%>
  <%= form.label :gender, "Female"%>
  <%= form.radio_button :gender , class:"form-check"%>
  </td>
  <td>
  <%= form.label :contact_no %><br>
  <%= form.telephone_field :contact_no , class: "form-control"%>
  </td>
</tr>
<tr>
  <td>
  <%= form.label :father_name %><br>
  <%= form.text_field :father_name , class: "form-control"%>
  </td>
  <td>
  <%= form.label :mother_name %><br>
  <%= form.text_field :mother_name , class: "form-control"%>
  </td>
</tr>
<tr>
  <td>
  <%= form.label :father_contact_no %><br>
  <%= form.telephone_field :father_contact_no , class: "form-control"%>
  </td>
  <td>
  <%= form.label :mother_contact_no %><br>
  <%= form.telephone_field :mother_contact_no , class: "form-control"%>
  </td>
</tr>
</table>
</div>
<div class="container bg-light shadow p-3 mb-5 bg-white rounded">
<h4> Address Details </h4>
<table class="table">
<tr>
  <td>
  <%= form.label :house_no %><br>
  <%= form.text_field :house_no , class: "form-control"%>
  </td>
  <td>
  <%= form.label :area_lankmark %><br>
  <%= form.text_field :area_lankmark , class: "form-control"%>
  </td>
</tr>
<tr>
  <td>
  <%= form.label :city %><br>
  <%= form.text_field :city , class: "form-control"%>
  </td>
  <td>
  <%= form.label :pin_code %><br>
  <%= form.text_field :pin_code , class: "form-control"%>
  </td>
 <td>
  <%= form.label :state %>
  <%= form.text_field :state , class: "form-control"%>
  </td>
</tr>

</table>
<%= form.submit  class:"btn btn-success" %>
</div>

<% end %>


</body>
</html>

app/views/employees/show.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Employee Portal</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-dark bg-dark ">
<strong><h3 class="text-white"> Employee<snap class="text-primary">Portal<snap></h3></strong>
</nav>
<h3 class="text-center">Employee Details </h3>
<div class="text-right" style="padding-right:250px">
<%= link_to 'Edit', edit_employee_path(@employee), class:"btn btn-warning"%>
<%= link_to 'Delete', employee_path(@employee),data:{
  turbo_method: :delete, turbo_confirm: "Are you sure?"
}, class:"btn btn-danger"%>
<%= link_to 'Back', root_path, class:"btn btn-primary"%>
</div>
<div class="container bg-light shadow p-3 mb-5 bg-white rounded">
<h4>Employee Details</h4>
<table class="table">
<tr>
<td>
<strong>Name</strong>
<p><%= @employee.name %></p>
</td>
<td>
<strong>Email</strong>
<p><%= @employee.email %></p>
</td>
<td>
<strong>Designation</strong>
<p><%= @employee.designation %></p>
</td>
</tr>
<tr>
<td>
<strong>Joining date</strong>
<p><%= @employee.joining_date %></p>
</td>
<td>
<strong>Company name</strong>
<p><%= @employee.company_name %></p>
</td>
<td>
<strong>Company Address</strong>
<p><%= @employee.company_address %></p>
</td>
</tr>
</table>
</div>

<div class="container bg-light shadow p-3 mb-5 bg-white rounded">
<h4>Personal Details</h4>
<table class="table">
<tr>
<td>
<strong>Date of birth</strong>
<p><%= @employee.date_of_birth %></p>
</td>
<td>
<strong>Gender</strong>
<p><%= @employee.gender %></p>
</td>
<td>
<strong>Contact Number</strong>
<p><%= @employee.contact_no %></p>
</td>
</tr>
<tr>
<td>
<strong>Father Name</strong>
<p><%= @employee.father_name %></p>
</td>
<td>
<strong>Mother name</strong>
<p><%= @employee.mother_name %></p>
</td>
<td>
<strong>Father contact number</strong>
<p><%= @employee.father_contact_no %></p>
</td>
</tr>
<tr>
<td>
<strong>Mother contact number</strong>
<p><%= @employee.mother_contact_no %></p>
</td>
</tr>
</table>
</div>

<div class="container bg-light shadow p-3 mb-5 bg-white rounded">
<h4>Address Details</h4>
<table class="table">
<tr>
<td>
<strong>House no</strong>
<p><%= @employee.house_no %></p>
</td>
<td>
<strong>Area landmark</strong>
<p><%= @employee.area_lankmark %></p>
</td>
<td>
<strong>City</strong>
<p><%= @employee.city %></p>
</td>
</tr>
<tr>
<td>
<strong>Pin Code</strong>
<p><%= @employee.pin_code %></p>
</td>
<td>
<strong>State</strong>
<p><%= @employee.state %></p>
</td>
</tr>
</table>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeePortal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" type="image/x-icon" href="https://benpor.com/wp-content/uploads/2014/11/employee-portal.jpg">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>